Issue/5993 add dedicated pip index url for full project
inmanta/pytest-inmanta pull request #396
Opened 2023-06-22 15:15 UTC by Hugo-Inmanta

# Description

Part of https://github.com/inmanta/inmanta-core/issues/5993

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-06-23 08:25 UTC, sanderr requested changes
I'm not sure this suffices. We have to think about compatibility here. What do we want this `--pip-index-url` option for `pytest-inmanta` to represent?
1. Current implementation: it sets the `pip.index_url` config option that is only available on the latest version of core.
2. Backwards compatibility approach: it is pytest-inmanta's setting to set the pip index url: on new versions of core it sets `pip.index_url`, on older versions it falls back to adding a v2 package index. This also means we deprecate setting it through the module repo option.

I am personally in favor of 2. There is something to say for 1 (new config option -> new cli option) but I think it could be very unintuitive for an end-user.

2023-06-23 08:25 UTC, sanderr commented on pytest_inmanta/parameters.py
> +    environment_variable="INMANTA_PIP_INDEX_URL",
Nice! I already have this env var set.

2023-06-23 08:25 UTC, sanderr commented on pytest_inmanta/parameters.py
> +    usage=("List of project-wide pip indexes"),
```suggestion
    usage="List of project-wide pip indexes",
```
These are redundant.

2023-06-26 12:34 UTC, sanderr requested changes

2023-06-26 12:34 UTC, sanderr commented on pytest_inmanta/__init__.py
Perhaps put this in `pytest_inmanta.core`?

2023-06-26 12:34 UTC, sanderr commented on pytest_inmanta/__init__.py
> +CORE_VERSION: Optional[version.Version]
In the test code I would import this file instead of doing it over there.

FYI: inmanta/inmanta-core#6175

2023-06-26 12:34 UTC, sanderr commented on pytest_inmanta/plugin.py
> +from . import SUPPORTS_PROJECT_PIP_INDEX
We don't generally use relative imports.

2023-06-26 12:34 UTC, sanderr commented on pytest_inmanta/__init__.py
> +    CORE_VERSION is not None and CORE_VERSION >= version.Version("9.2.0.dev")
```suggestion
    CORE_VERSION is not None and CORE_VERSION >= version.Version("9.3.0.dev")
```
We will delay the merge until after the release. This means you will also need to do a minor bump on core (the release process will only make it `9.2.1`.

2023-06-26 12:34 UTC, sanderr commented on pytest_inmanta/plugin.py
> +        pip_config: ProjectPipConfig = ProjectPipConfig(index_url=list(pip_index_urls))
We should ensure backwards compatibility in the other direction as well: if the user still uses the deprecated option we should supply it to `pip.index_url`.

2023-06-28 13:04 UTC, sanderr requested changes

2023-06-28 13:04 UTC, sanderr commented on pytest_inmanta/plugin.py
> +            index_url=list(set(list(index_urls) + repos_urls))
Same comment about set and insertion order here.

2023-06-28 14:35 UTC, Hugo-Inmanta commented
I still have some mypy errors: 

```
+ pytest_inmanta/plugin.py:285: error: Value of type "object" is not indexable  [index]
+ pytest_inmanta/plugin.py:287: error: Value of type "object" is not indexable  [index]
+ pytest_inmanta/plugin.py:302: error: Argument "install_mode" to "ProjectMetadata" has incompatible type "Union[str, str, str]"; expected "InstallMode"  [arg-type]
+ pytest_inmanta/plugin.py:312: error: Argument "repo" to "ProjectMetadata" has incompatible type "list[object]"; expected "list[ModuleRepoInfo]"  [arg-type]
```

2023-06-28 14:52 UTC, sanderr requested changes
About the mypy errors: those seem to be a side effect of the fact that we need to support multiple versions of core. Until we can clean that up I think we can leave most of it as is, because we do have pydantic validation, even if mypy doesn't recognize it. There is one part that we may need to address now: I think the current implementation may break on iso4 if `index_urls` is set because you add them as v2 source repos, and iso4 (iirc, should be checked) only accepts strings.
- typing this correctly is more difficult because it depends on the version of core, so we could consider most of that out of scope until we can clean this up. But I think it might be good to

2023-06-28 15:24 UTC, sanderr approved these changes

2023-06-29 07:03 UTC, merged