automate release
inmanta/pytest-inmanta pull request #99
Opened 2020-09-07 14:13 UTC by sanderr

# Description

Automates release by using generic Jenkins file from inmanta/irt#236.
After merge, Jenkins job should be updated.

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] ~~Changelog entry~~
- [x] ~~Code is clear and sufficiently documented~~
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2020-09-07 14:27 UTC, arnaudsjs approved these changes

2020-09-08 05:45 UTC, arnaudsjs requested changes
Also add a question mark in the changelog as a placeholder for the release date.

2020-09-08 08:16 UTC, arnaudsjs approved these changes

2020-09-08 08:28 UTC, andraskvr approved these changes

2020-09-08 08:30 UTC, merged